### ISSUE TITLE
Plugin menu straight crashes the game

### ISSUE THREAD

**Issue by Pdzly** [djsime1/menu-plugins-redux#14]
If you are ingame and click the plugins button it straight crashes the game

**Comment by djsime1** [comment]
What commit is this occuring on and what GMod branch are you using?

**Comment by djsime1** [comment]
Also does it still crash if you run `menup gui` in console instead?

**Comment by Pdzly** [comment]
sorry for the delayed answer i will try it rn

**Comment by Pdzly** [comment]
No it wont crash

**Comment by Pdzly** [comment]
> What commit is this occuring on and what GMod branch are you using?

Gmod x86-64 - Chromium + 64 Bit binaries

**Comment by Pdzly** [comment]
> Also does it still crash if you run `menup gui` in console instead?

Ok i tested it it crashes if you never did the console command menup gui but if you did it once it wont crash

**Comment by djsime1** [comment]
Attempted to address this issue in the latest dev branch update. Please re-open if it continues to crash after updating.
