### ISSUE TITLE
Prevent Update Popup from Getting stuck on Menu_Reload while in a game

### ISSUE THREAD

**Issue by VCSoldier** [djsime1/menu-plugins-redux#2]
if the update popup is shown while in a server/singleplayer world  and you run the concmd "menu_reload" the popup will be stuck in the pause menu until disconnect.

**Comment by djsime1** [comment]
menu_reload is a hacky command I used for early development and I plan on entirely replacing menu_dev.lua soon. Reloading the menu while in game is known to cause issues as well. I wrote some new concommands to work around this. You can use `menup load [id/file]` to reload an individual plugin, or `menup restart` to restart the entire MPR framework (but not the entire menu.)

**Comment by djsime1** [comment]
Closing since that command is going to be phased out.
