### ISSUE TITLE
Manual server blacklist

### ISSUE THREAD

**Issue by YohSambre** [djsime1/menu-plugins-redux#3]
first of all I have to thank the development team for this great work, I really like your version of the plugins menu and I use it now on a daily basis, in short I had an idea for a plugin for motivated developers,

a plugin to blacklist some servers (I'm so tired of seeing founders stealing my ip to ddos me or geolocate me or some hacker who backdoor servers and try to get information about me)

I think I've described the essentials, a plugin to avoid a lot of malicious servers..

**Comment by djsime1** [comment]
While the implementation would be somewhat scuffed, it is possible. The difficulty comes if you want this to be a crowdsourced list, where other users can report certain servers as being malicious. I could probably write up a quick solution that lets you manually specify which IP's are blocked, however anything beyond that would require a lot of effort.

**Comment by YohSambre** [comment]
> While the implementation would be somewhat scuffed, it is possible. The difficulty comes if you want this to be a crowdsourced list, where other users can report certain servers as being malicious. I could probably write up a quick solution that lets you manually specify which IP's are blocked, however anything beyond that would require a lot of effort.

I am very interested by your solution, concerning the fact of sharing in a community way I think that for the moment it is useless..if really the public which uses menu-plugins-redux evolves and starts to be massive there is a very simple solution > a channel discord of sharing of ip.

**Comment by djsime1** [comment]
Implemented as part of Custom Server Blacklist plugin in latest dev branch update.
