### ISSUE TITLE
Mini games plugin

### ISSUE THREAD

**Issue by YohSambre** [djsime1/menu-plugins-redux#4]
who has never dreamed of playing snake or flappy bird in the gmod menu ?, frankly a plugin filled with mini games could be very fun

**Comment by djsime1** [comment]
The original menu plugin repo already has [a Snake plugin](https://github.com/glua/gmod-menu-plugins/blob/master/lua/menu_plugins/default/snake.lua) you can use. It's compatible with MPR and once installed, it will appear as a "Legacy plugin."
As for adding other mini games, that's not something I'll do. If you want to write some and open a Pull Request, then I'll accept it.

**Comment by YohSambre** [comment]
> The original menu plugin repo already has [a Snake plugin](https://github.com/glua/gmod-menu-plugins/blob/master/lua/menu_plugins/default/snake.lua) you can use. It's compatible with MPR and once installed, it will appear as a "Legacy plugin." As for adding other mini games, that's not something I'll do. If you want to write some and open a Pull Request, then I'll accept it.

Thanks for the link I added it, I can finally play in a game in a game !
