### ISSUE TITLE
Loading music

### ISSUE THREAD

**Issue by WildToastyMop** [djsime1/menu-plugins-redux#5]
I think a plugin that just muted loading screens somehow would be awesome I still want to be able to see the loading screen I just don't want to hear their god awful music and before anyone says that's what volume mixer is for, gmod likes to freeze volume mixer when loading into a game for some reason and this way it would be automatic too.

**Comment by djsime1** [comment]
This is definitely possible, I'll try to write something that can do this, and probably other things like overriding the loading URL and/or spoofing your SteamID.

**Comment by YohSambre** [comment]
it is already possible to block custom loading screens, it is located in the gmod options

proof:
https://zupimages.net/up/22/06/pb3k.png

remark it would be nice to have more customization than the simple default screen of gmod..

**Comment by djsime1** [comment]
As mentioned previously, the best I could do is allow you to mute the loading screen, spoof your SteamID, and outright replace it with your own URL or the default loading screen.

**Comment by YohSambre** [comment]
> As mentioned previously, the best I could do is allow you to mute the loading screen, spoof your SteamID, and outright replace it with your own URL or the default loading screen.

possible to spoof the ip in addition to the steamid?

**Comment by djsime1** [comment]
> possible to spoof the ip in addition to the steamid?

Yea that's simply not possible without a VPN or akin product. My personal recommendation is Mullvad if you're on a budget.

**Comment by Pdzly** [comment]
But is it possible to spoof the parameters that are getting called on the loading screen?

**Comment by djsime1** [comment]
> But is it possible to spoof the parameters that are getting called on the loading screen?
> 

I put "Added loading screen customizer" in the latest changelog but forgot to actually add the file... I'll get out the actual plugin in the next commit. It will have the ability to spoof the SteamID, but I don't see a reason to make it spoof anything else.

**Comment by djsime1** [comment]
Implemented as part of Loading Screen Modifier plugin in latest dev branch update.
