### ISSUE TITLE
Personalized Disconnect Message

### ISSUE THREAD

**Issue by YohSambre** [djsime1/menu-plugins-redux#6]
I remember many videos showing this feature, it would be very fun to be able to customize the Disconnect Message to make others intrigued to see that a person has just disconnected with the reason "I do not like this server".

https://youtu.be/xsC8GtSWuyU

**Comment by djsime1** [comment]
This framework isn't magic, and it's really not much more than a glorified script runner. That is a CS:S video from 2009. The same does not apply to Garry's Mod in 2022. All menu plugins are limited to the menu realm. While there are special modules that can give you the ability to run Lua in the client realm, I will not supply any resources with regards to "hacking" the client realm. Therefore, this request is impossible to fulfill with just a single Lua plugin. Kindly take this request to your local script kiddie forum, and try begging there.

**Comment by vurvdev** [comment]
Pretty rude. Could have simply not known whether this is possible through the menu

**Comment by Pdzly** [comment]
> Pretty rude. Could have simply not known whether this is possible through the menu

It might be possible through hacky ways but this plugin loader isnt planned to such things
