### ISSUE TITLE
Hook when game is quit

### ISSUE THREAD

**Issue by Pdzly** [djsime1/menu-plugins-redux#9]
Is there a way to hook if gmod is closing?

**Comment by Pdzly** [comment]
https://wiki.facepunch.com/gmod/GM:ShutDown
But its just for Client or Server Realm

**Comment by djsime1** [comment]
While that hook is only in client/server, we are in the same realm as the "Quit" button... I'll look into it!

**Comment by Pdzly** [comment]
Ok thanks! a lot!

**Comment by djsime1** [comment]
Internally it calls `RunGameUICommand("quit")`, and it seems like other custom menus do the same, so it will be easy to hook.

**Comment by Pdzly** [comment]
How is it done ? if i am allowed to ask? 
My idea to overwrite RunGameUICommand like:

local oldRunGame = RunGameUICommand
function RunGameUICommand(cmd)
if(cmd == "quit") then
dooshithere
end
oldRunGame(cmd)
end

or are you going to make a hook

**Comment by djsime1** [comment]
Yeah that will essentially be it, except the `dooshithere` will be something like `hook.Run("MenuQuit")`.

**Comment by Pdzly** [comment]
Ok perfect thanks for the fast response :)

**Comment by djsime1** [comment]
Just added a hook in the latest commit. If you already overrode `RunGameUICommand` in one of your plugins, I'd recommend replacing it with a `ShutDown` hook.
https://github.com/djsime1/menu-plugins-redux/wiki/Hooks#shutdown
